#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "lvgl.h"
#include "owl_ui.h"

#define OWL_COLOR_BG lv_color_hex(0x000000)
#define OWL_COLOR_CREAM lv_color_hex(0xF4EDE1)
#define OWL_COLOR_AMBER lv_color_hex(0xFFB627)
#define OWL_COLOR_BARK lv_color_hex(0x2F2A26)
#define OWL_COLOR_MUTED lv_color_hex(0xA89F94)
#define OWL_COLOR_DIM lv_color_hex(0x5C554D)

/* Inter with Latin, Greek and Cyrillic coverage (fonts/, generated by tools/gen_fonts.sh). */
LV_FONT_DECLARE(owl_font_14)
LV_FONT_DECLARE(owl_font_20)
LV_FONT_DECLARE(owl_font_28)

/* Full-screen transparent container for one page. */
lv_obj_t *owl_ui_page(lv_obj_t *parent);
/* Plain filled rectangle with none of the theme's styling, not clickable. */
lv_obj_t *owl_ui_box(lv_obj_t *parent, int32_t w, int32_t h, lv_color_t color, int32_t radius);
/* Centred label. width > 0 makes it a single line that ends in "..." when too long. */
lv_obj_t *owl_ui_label(lv_obj_t *parent, const lv_font_t *font, lv_color_t color, int32_t width);
/* Change-only setters: they leave the widget alone (no redraw) when the value is the same. */
void owl_ui_set_text(lv_obj_t *label, const char *text);
void owl_ui_set_text_color(lv_obj_t *obj, lv_color_t color);
void owl_ui_set_arc_color(lv_obj_t *arc, lv_color_t color);
void owl_ui_show(lv_obj_t *obj, bool visible);
const char *owl_ui_battery_symbol(uint8_t percent, bool charging);
/* Full-circle arc around the screen edge, range 0..1000, no knob. */
lv_obj_t *owl_ui_ring(lv_obj_t *parent, int32_t width, lv_color_t track, lv_color_t fill);

typedef enum { OWL_MOOD_AWAKE, OWL_MOOD_DROWSY, OWL_MOOD_SCANNING, OWL_MOOD_SLEEPY, OWL_MOOD_ASLEEP } owl_mood_t;

lv_obj_t *owl_eyes_create(lv_obj_t *parent);
/* gaze_x, gaze_y: -100..100, where the pupils look. */
void owl_eyes_set(lv_obj_t *eyes, owl_mood_t mood, int32_t gaze_x, int32_t gaze_y);

typedef struct {
    lv_obj_t *root;
    lv_obj_t *progress;
    lv_obj_t *volume;
    lv_obj_t *art;
    lv_obj_t *art_placeholder;
    lv_obj_t *title;
    lv_obj_t *subtitle;
    lv_obj_t *liked;
    lv_obj_t *brand;
    lv_obj_t *status;
    lv_obj_t *eyes;
    lv_obj_t *message;
    lv_obj_t *hint;
} owl_np_page_t;

void owl_np_create(owl_np_page_t *pg, lv_obj_t *parent);
void owl_np_render(owl_np_page_t *pg, const owl_app_t *app, const owl_player_t *p, const owl_ui_inputs_t *in,
                   int64_t now_ms);

typedef struct {
    lv_obj_t *root;
    lv_obj_t *heading;
    lv_obj_t *rows[5]; /* rows[2] is the selected row */
    lv_obj_t *sub;     /* subtitle of the selected row */
    lv_obj_t *position;
    lv_obj_t *empty;
} owl_list_ui_t;

void owl_list_ui_create(owl_list_ui_t *pg, lv_obj_t *parent);
void owl_list_ui_render(owl_list_ui_t *pg, const owl_app_t *app);
